/*
 * @copyright Copyright (c) 2022 Woven Alpha, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <map>
#include <memory>
#include <string>

#include <linux/input-event-codes.h>

/*
 * NOTES:
 *   the following comment out entries are not supported.
 */
#if defined(BUILD_UNORDERED_MAP)
static const std::unordered_map<uint32_t, uint32_t> map_xkb_key_to_fl_snancode = {
#else
static const std::map<uint32_t, uint32_t> map_xkb_key_to_fl_snancode = {
#endif
  //{ KEY_RESERVED,
  { KEY_ESC, 256 },
  { KEY_1, 49 },
  { KEY_2, 50 },
  { KEY_3, 51 },
  { KEY_4, 52 },
  { KEY_5, 53 },
  { KEY_6, 54 },
  { KEY_7, 55 },
  { KEY_8, 56 },
  { KEY_9, 57 },
  { KEY_0, 48 },
  { KEY_MINUS, 45 },
  { KEY_EQUAL, 61 },
  { KEY_BACKSPACE, 259 },
  { KEY_TAB, 258 },
  { KEY_Q, 81 },
  { KEY_W, 87 },
  { KEY_E, 69 },
  { KEY_R, 82 },
  { KEY_T, 84 },
  { KEY_Y, 89 },
  { KEY_U, 85 },
  { KEY_I, 73 },
  { KEY_O, 79 },
  { KEY_P, 80 },
  { KEY_LEFTBRACE, 91 },
  { KEY_RIGHTBRACE, 93 },
  { KEY_ENTER, 257 },
  { KEY_LEFTCTRL, 341 },
  { KEY_A, 65 },
  { KEY_S, 83 },
  { KEY_D, 68 },
  { KEY_F, 70 },
  { KEY_G, 71 },
  { KEY_H, 72 },
  { KEY_J, 74 },
  { KEY_K, 75 },
  { KEY_L, 76 },
  { KEY_SEMICOLON, 59 },
  { KEY_APOSTROPHE, 39 },
  { KEY_GRAVE, 96 },
  { KEY_LEFTSHIFT, 340 },
  { KEY_BACKSLASH, 92 },
  { KEY_Z, 90 },
  { KEY_X, 88 },
  { KEY_C, 67 },
  { KEY_V, 86 },
  { KEY_B, 66 },
  { KEY_N, 78 },
  { KEY_M, 77 },
  { KEY_COMMA, 44 },
  { KEY_DOT, 46 },
  { KEY_SLASH, 47 },
  { KEY_RIGHTSHIFT, 344 },
//  { KEY_KPASTERISK,
  { KEY_LEFTALT, 342 },
  { KEY_SPACE, 32 },
  { KEY_CAPSLOCK, 280 },
  { KEY_F1, 290 },
  { KEY_F2, 291 },
  { KEY_F3, 292 },
  { KEY_F4, 293 },
  { KEY_F5, 294 },
  { KEY_F6, 295 },
  { KEY_F7, 296 },
  { KEY_F8, 297 },
  { KEY_F9, 298 },
  { KEY_F10, 299 },
  { KEY_NUMLOCK, 282 },
  { KEY_SCROLLLOCK, 281 },
  { KEY_KP7, 327 },
  { KEY_KP8, 328 },
  { KEY_KP9, 329 },
  { KEY_KPMINUS, 333 },
  { KEY_KP4, 324 },
  { KEY_KP5, 325 },
  { KEY_KP6, 326 },
  { KEY_KPPLUS, 334 },
  { KEY_KP1, 321 },
  { KEY_KP2, 322 },
  { KEY_KP3, 323 },
  { KEY_KP0, 320 },
  { KEY_KPDOT, 332 },
//  { KEY_ZENKAKUHANKAKU,
//  { KEY_102ND,
  { KEY_F11, 300 },
  { KEY_F12, 301 },
//  { KEY_RO,
//  { KEY_KATAKANA,
//  { KEY_HIRAGANA,
//  { KEY_HENKAN,
//  { KEY_KATAKANAHIRAGANA,
//  { KEY_MUHENKAN,
//  { KEY_KPJPCOMMA,
  { KEY_KPENTER, 335 },
  { KEY_RIGHTCTRL, 345 },
  { KEY_KPSLASH, 331 },
//  { KEY_SYSRQ,
  { KEY_RIGHTALT, 346 },
//  { KEY_LINEFEED,
  { KEY_HOME, 268 },
  { KEY_UP, 265 },
  { KEY_PAGEUP, 266 },
  { KEY_LEFT, 263 },
  { KEY_RIGHT, 262 },
  { KEY_END, 269 },
  { KEY_DOWN, 264 },
  { KEY_PAGEDOWN, 267 },
  { KEY_INSERT,260 },
  { KEY_DELETE, 261 },
//  { KEY_MACRO,
//  { KEY_MUTE,
//  { KEY_VOLUMEDOWN,
//  { KEY_VOLUMEUP,
//  { KEY_POWER,
  { KEY_KPEQUAL, 336 },
//  { KEY_KPPLUSMINUS,
  { KEY_PAUSE, 284 },
//  { KEY_SCALE,
  { KEY_KPCOMMA, 330 },
//  { KEY_HANGEUL,
//  { KEY_HANJA,
//  { KEY_YEN,
  { KEY_LEFTMETA, 343 },
  { KEY_RIGHTMETA, 347 },
//  { KEY_COMPOSE,
//  { KEY_STOP,
//  { KEY_AGAIN,
//  { KEY_PROPS,
//  { KEY_UNDO,
//  { KEY_FRONT,
//  { KEY_COPY,
//  { KEY_OPEN,
//  { KEY_PASTE,
//  { KEY_FIND,
//  { KEY_CUT,
//  { KEY_HELP,
  { KEY_MENU, 348 },
//  { KEY_CALC,
//  { KEY_SETUP,
//  { KEY_SLEEP,
//  { KEY_WAKEUP,
//  { KEY_FILE,
//  { KEY_SENDFILE,
//  { KEY_DELETEFILE,
//  { KEY_XFER,
//  { KEY_PROG1,
//  { KEY_PROG2,
//  { KEY_WWW,
//  { KEY_MSDOS,
//  { KEY_COFFEE,
//  { KEY_ROTATE_DISPLAY,
//  { KEY_CYCLEWINDOWS,
//  { KEY_MAIL,
//  { KEY_BOOKMARKS,
//  { KEY_COMPUTER,
//  { KEY_BACK,
//  { KEY_FORWARD,
//  { KEY_CLOSECD,
//  { KEY_EJECTCD,
//  { KEY_EJECTCLOSECD,
//  { KEY_NEXTSONG,
//  { KEY_PLAYPAUSE,
//  { KEY_PREVIOUSSONG,
//  { KEY_STOPCD,
//  { KEY_RECORD,
//  { KEY_REWIND,
//  { KEY_PHONE,
//  { KEY_ISO,
//  { KEY_CONFIG,
//  { KEY_HOMEPAGE,
//  { KEY_REFRESH,
//  { KEY_EXIT,
//  { KEY_MOVE,
//  { KEY_EDIT,
//  { KEY_SCROLLUP,
//  { KEY_SCROLLDOWN,
//  { KEY_KPLEFTPAREN,
//  { KEY_KPRIGHTPAREN,
//  { KEY_NEW,
//  { KEY_REDO,
  { KEY_F13, 302 },
  { KEY_F14, 303 },
  { KEY_F15, 304 },
  { KEY_F16, 305 },
  { KEY_F17, 306 },
  { KEY_F18, 307 },
  { KEY_F19, 308 },
  { KEY_F20, 309 },
  { KEY_F21, 310 },
  { KEY_F22, 311 },
  { KEY_F23, 312 },
  { KEY_F24, 313 },
//  { KEY_PLAYCD,
//  { KEY_PAUSECD,
//  { KEY_PROG3,
//  { KEY_PROG4,
//  { KEY_ALL_APPLICATIONS,
//  { KEY_SUSPEND,
//  { KEY_CLOSE,
//  { KEY_PLAY,
//  { KEY_FASTFORWARD,
//  { KEY_BASSBOOST,
  { KEY_PRINT, 283 },
//  { KEY_HP,
//  { KEY_CAMERA,
//  { KEY_SOUND,
//  { KEY_QUESTION,
//  { KEY_EMAIL,
//  { KEY_CHAT,
//  { KEY_SEARCH,
//  { KEY_CONNECT,
//  { KEY_FINANCE,
//  { KEY_SPORT,
//  { KEY_SHOP,
//  { KEY_ALTERASE,
//  { KEY_CANCEL,
//  { KEY_BRIGHTNESSDOWN,
//  { KEY_BRIGHTNESSUP,
//  { KEY_MEDIA,
//  { KEY_SWITCHVIDEOMODE,
//  { KEY_KBDILLUMTOGGLE,
//  { KEY_KBDILLUMDOWN,
//  { KEY_KBDILLUMUP,
//  { KEY_SEND,
//  { KEY_REPLY,
//  { KEY_FORWARDMAIL,
//  { KEY_SAVE,
//  { KEY_DOCUMENTS,
//  { KEY_BATTERY,
//  { KEY_BLUETOOTH,
//  { KEY_WLAN,
//  { KEY_UWB,
//  { KEY_UNKNOWN,
//  { KEY_VIDEO_NEXT,
//  { KEY_VIDEO_PREV,
//  { KEY_BRIGHTNESS_CYCLE,
//  { KEY_BRIGHTNESS_AUTO,
//  { KEY_DISPLAY_OFF,
//  { KEY_WWAN,
//  { KEY_RFKILL,
//  { KEY_MICMUTE,
//  { BTN_MISC,
//  { BTN_0,
//  { BTN_1,
//  { BTN_2,
//  { BTN_3,
//  { BTN_4,
//  { BTN_5,
//  { BTN_6,
//  { BTN_7,
//  { BTN_8,
//  { BTN_9,
//  { BTN_MOUSE,
//  { BTN_LEFT,
//  { BTN_RIGHT,
//  { BTN_MIDDLE,
//  { BTN_SIDE,
//  { BTN_EXTRA,
//  { BTN_FORWARD,
//  { BTN_BACK,
//  { BTN_TASK,
//  { BTN_JOYSTICK,
//  { BTN_TRIGGER,
//  { BTN_THUMB,
//  { BTN_THUMB2,
//  { BTN_TOP,
//  { BTN_TOP2,
//  { BTN_PINKIE,
//  { BTN_BASE,
//  { BTN_BASE2,
//  { BTN_BASE3,
//  { BTN_BASE4,
//  { BTN_BASE5,
//  { BTN_BASE6,
//  { BTN_DEAD,
//  { BTN_GAMEPAD,
//  { BTN_SOUTH,
//  { BTN_EAST,
//  { BTN_C,
//  { BTN_NORTH,
//  { BTN_WEST,
//  { BTN_Z,
//  { BTN_TL,
//  { BTN_TR,
//  { BTN_TL2,
//  { BTN_TR2,
//  { BTN_SELECT,
//  { BTN_START,
//  { BTN_MODE,
//  { BTN_THUMBL,
//  { BTN_THUMBR,
//  { BTN_DIGI,
//  { BTN_TOOL_PEN,
//  { BTN_TOOL_RUBBER,
//  { BTN_TOOL_BRUSH,
//  { BTN_TOOL_PENCIL,
//  { BTN_TOOL_AIRBRUSH,
//  { BTN_TOOL_FINGER,
//  { BTN_TOOL_MOUSE,
//  { BTN_TOOL_LENS,
//  { BTN_TOOL_QUINTTAP,
//  { BTN_STYLUS3,
//  { BTN_TOUCH,
//  { BTN_STYLUS,
//  { BTN_STYLUS2,
//  { BTN_TOOL_DOUBLETAP,
//  { BTN_TOOL_TRIPLETAP,
//  { BTN_TOOL_QUADTAP,
//  { BTN_WHEEL,
//  { BTN_GEAR_DOWN,
//  { BTN_GEAR_UP,
//  { KEY_OK,
//  { KEY_SELECT,
//  { KEY_GOTO,
//  { KEY_CLEAR,
//  { KEY_POWER2,
//  { KEY_OPTION,
//  { KEY_INFO,
//  { KEY_TIME,
//  { KEY_VENDOR,
//  { KEY_ARCHIVE,
//  { KEY_PROGRAM,
//  { KEY_CHANNEL,
//  { KEY_FAVORITES,
//  { KEY_EPG,
//  { KEY_PVR,
//  { KEY_MHP,
//  { KEY_LANGUAGE,
//  { KEY_TITLE,
//  { KEY_SUBTITLE,
//  { KEY_ANGLE,
//  { KEY_FULL_SCREEN,
//  { KEY_MODE,
//  { KEY_KEYBOARD,
//  { KEY_ASPECT_RATIO,
//  { KEY_PC,
//  { KEY_TV,
//  { KEY_TV2,
//  { KEY_VCR,
//  { KEY_VCR2,
//  { KEY_SAT,
//  { KEY_SAT2,
//  { KEY_CD,
//  { KEY_TAPE,
//  { KEY_RADIO,
//  { KEY_TUNER,
//  { KEY_PLAYER,
//  { KEY_TEXT,
//  { KEY_DVD,
//  { KEY_AUX,
//  { KEY_MP3,
//  { KEY_AUDIO,
//  { KEY_VIDEO,
//  { KEY_DIRECTORY,
//  { KEY_LIST,
//  { KEY_MEMO,
//  { KEY_CALENDAR,
//  { KEY_RED,
//  { KEY_GREEN,
//  { KEY_YELLOW,
//  { KEY_BLUE,
//  { KEY_CHANNELUP,
//  { KEY_CHANNELDOWN,
//  { KEY_FIRST,
//  { KEY_LAST,
//  { KEY_AB,
//  { KEY_NEXT,
//  { KEY_RESTART,
//  { KEY_SLOW,
//  { KEY_SHUFFLE,
//  { KEY_BREAK,
//  { KEY_PREVIOUS,
//  { KEY_DIGITS,
//  { KEY_TEEN,
//  { KEY_TWEN,
//  { KEY_VIDEOPHONE,
//  { KEY_GAMES,
//  { KEY_ZOOMIN,
//  { KEY_ZOOMOUT,
//  { KEY_ZOOMRESET,
//  { KEY_WORDPROCESSOR,
//  { KEY_EDITOR,
//  { KEY_SPREADSHEET,
//  { KEY_GRAPHICSEDITOR,
//  { KEY_PRESENTATION,
//  { KEY_DATABASE,
//  { KEY_NEWS,
//  { KEY_VOICEMAIL,
//  { KEY_ADDRESSBOOK,
//  { KEY_MESSENGER,
//  { KEY_DISPLAYTOGGLE,
//  { KEY_SPELLCHECK,
//  { KEY_LOGOFF,
//  { KEY_DOLLAR,
//  { KEY_EURO,
//  { KEY_FRAMEBACK,
//  { KEY_FRAMEFORWARD,
//  { KEY_CONTEXT_MENU,
//  { KEY_MEDIA_REPEAT,
//  { KEY_10CHANNELSUP,
//  { KEY_10CHANNELSDOWN,
//  { KEY_IMAGES,
//  { KEY_NOTIFICATION_CENTER,
//  { KEY_PICKUP_PHONE,
//  { KEY_HANGUP_PHONE,
//  { KEY_DEL_EOL,
//  { KEY_DEL_EOS,
//  { KEY_INS_LINE,
//  { KEY_DEL_LINE,
//  { KEY_FN,
//  { KEY_FN_ESC,
//  { KEY_FN_F1,
//  { KEY_FN_F2,
//  { KEY_FN_F3,
//  { KEY_FN_F4,
//  { KEY_FN_F5,
//  { KEY_FN_F6,
//  { KEY_FN_F7,
//  { KEY_FN_F8,
//  { KEY_FN_F9,
//  { KEY_FN_F10,
//  { KEY_FN_F11,
//  { KEY_FN_F12,
//  { KEY_FN_1,
//  { KEY_FN_2,
//  { KEY_FN_D,
//  { KEY_FN_E,
//  { KEY_FN_F,
//  { KEY_FN_S,
//  { KEY_FN_B,
//  { KEY_FN_RIGHT_SHIFT,
//  { KEY_BRL_DOT1,
//  { KEY_BRL_DOT2,
//  { KEY_BRL_DOT3,
//  { KEY_BRL_DOT4,
//  { KEY_BRL_DOT5,
//  { KEY_BRL_DOT6,
//  { KEY_BRL_DOT7,
//  { KEY_BRL_DOT8,
//  { KEY_BRL_DOT9,
//  { KEY_BRL_DOT10,
//  { KEY_NUMERIC_0,
//  { KEY_NUMERIC_1,
//  { KEY_NUMERIC_2,
//  { KEY_NUMERIC_3,
//  { KEY_NUMERIC_4,
//  { KEY_NUMERIC_5,
//  { KEY_NUMERIC_6,
//  { KEY_NUMERIC_7,
//  { KEY_NUMERIC_8,
//  { KEY_NUMERIC_9,
//  { KEY_NUMERIC_STAR,
//  { KEY_NUMERIC_POUND,
//  { KEY_NUMERIC_A,
//  { KEY_NUMERIC_B,
//  { KEY_NUMERIC_C,
//  { KEY_NUMERIC_D,
//  { KEY_CAMERA_FOCUS,
//  { KEY_WPS_BUTTON,
//  { KEY_TOUCHPAD_TOGGLE,
//  { KEY_TOUCHPAD_ON,
//  { KEY_TOUCHPAD_OFF,
//  { KEY_CAMERA_ZOOMIN,
//  { KEY_CAMERA_ZOOMOUT,
//  { KEY_CAMERA_UP,
//  { KEY_CAMERA_DOWN,
//  { KEY_CAMERA_LEFT,
//  { KEY_CAMERA_RIGHT,
//  { KEY_ATTENDANT_ON,
//  { KEY_ATTENDANT_OFF,
//  { KEY_ATTENDANT_TOGGLE,
//  { KEY_LIGHTS_TOGGLE,
//  { BTN_DPAD_UP,
//  { BTN_DPAD_DOWN,
//  { BTN_DPAD_LEFT,
//  { BTN_DPAD_RIGHT,
//  { KEY_ALS_TOGGLE,
//  { KEY_ROTATE_LOCK_TOGGLE,
//  { KEY_BUTTONCONFIG,
//  { KEY_TASKMANAGER,
//  { KEY_JOURNAL,
//  { KEY_CONTROLPANEL,
//  { KEY_APPSELECT,
//  { KEY_SCREENSAVER,
//  { KEY_VOICECOMMAND,
//  { KEY_ASSISTANT,
//  { KEY_KBD_LAYOUT_NEXT,
//  { KEY_EMOJI_PICKER,
//  { KEY_DICTATE,
//  { KEY_BRIGHTNESS_MIN,
//  { KEY_BRIGHTNESS_MAX,
//  { KEY_KBDINPUTASSIST_PREV,
//  { KEY_KBDINPUTASSIST_NEXT,
//  { KEY_KBDINPUTASSIST_PREVGROUP,
//  { KEY_KBDINPUTASSIST_NEXTGROUP,
//  { KEY_KBDINPUTASSIST_ACCEPT,
//  { KEY_KBDINPUTASSIST_CANCEL,
//  { KEY_RIGHT_UP,
//  { KEY_RIGHT_DOWN,
//  { KEY_LEFT_UP,
//  { KEY_LEFT_DOWN,
//  { KEY_ROOT_MENU,
//  { KEY_MEDIA_TOP_MENU,
//  { KEY_NUMERIC_11,
//  { KEY_NUMERIC_12,
//  { KEY_AUDIO_DESC,
//  { KEY_3D_MODE,
//  { KEY_NEXT_FAVORITE,
//  { KEY_STOP_RECORD,
//  { KEY_PAUSE_RECORD,
//  { KEY_VOD,
//  { KEY_UNMUTE,
//  { KEY_FASTREVERSE,
//  { KEY_SLOWREVERSE,
//  { KEY_DATA,
//  { KEY_ONSCREEN_KEYBOARD,
//  { KEY_PRIVACY_SCREEN_TOGGLE,
//  { KEY_SELECTIVE_SCREENSHOT,
//  { KEY_NEXT_ELEMENT ,
//  { KEY_PREVIOUS_ELEMENT ,
//  { KEY_AUTOPILOT_ENGAGE_TOGGLE,
//  { KEY_MARK_WAYPOINT,
//  { KEY_SOS,
//  { KEY_NAV_CHART,
//  { KEY_FISHING_CHART,
//  { KEY_SINGLE_RANGE_RADAR ,
//  { KEY_DUAL_RANGE_RADAR ,
//  { KEY_RADAR_OVERLAY,
//  { KEY_TRADITIONAL_SONAR,
//  { KEY_CLEARVU_SONAR,
//  { KEY_SIDEVU_SONAR ,
//  { KEY_NAV_INFO ,
//  { KEY_BRIGHTNESS_MENU,
//  { KEY_MACRO1,
//  { KEY_MACRO2,
//  { KEY_MACRO3,
//  { KEY_MACRO4,
//  { KEY_MACRO5,
//  { KEY_MACRO6,
//  { KEY_MACRO7,
//  { KEY_MACRO8,
//  { KEY_MACRO9,
//  { KEY_MACRO10,
//  { KEY_MACRO11,
//  { KEY_MACRO12,
//  { KEY_MACRO13,
//  { KEY_MACRO14,
//  { KEY_MACRO15,
//  { KEY_MACRO16,
//  { KEY_MACRO17,
//  { KEY_MACRO18,
//  { KEY_MACRO19,
//  { KEY_MACRO20,
//  { KEY_MACRO21,
//  { KEY_MACRO22,
//  { KEY_MACRO23,
//  { KEY_MACRO24,
//  { KEY_MACRO25,
//  { KEY_MACRO26,
//  { KEY_MACRO27,
//  { KEY_MACRO28,
//  { KEY_MACRO29,
//  { KEY_MACRO30,
//  { KEY_MACRO_RECORD_START,
//  { KEY_MACRO_RECORD_STOP,
//  { KEY_MACRO_PRESET_CYCLE,
//  { KEY_MACRO_PRESET1,
//  { KEY_MACRO_PRESET2,
//  { KEY_MACRO_PRESET3,
//  { KEY_KBD_LCD_MENU1,
//  { KEY_KBD_LCD_MENU2,
//  { KEY_KBD_LCD_MENU3,
//  { KEY_KBD_LCD_MENU4,
//  { KEY_KBD_LCD_MENU5,
//  { BTN_TRIGGER_HAPPY,
//  { BTN_TRIGGER_HAPPY1,
//  { BTN_TRIGGER_HAPPY2,
//  { BTN_TRIGGER_HAPPY3,
//  { BTN_TRIGGER_HAPPY4,
//  { BTN_TRIGGER_HAPPY5,
//  { BTN_TRIGGER_HAPPY6,
//  { BTN_TRIGGER_HAPPY7,
//  { BTN_TRIGGER_HAPPY8,
//  { BTN_TRIGGER_HAPPY9,
//  { BTN_TRIGGER_HAPPY10,
//  { BTN_TRIGGER_HAPPY11,
//  { BTN_TRIGGER_HAPPY12,
//  { BTN_TRIGGER_HAPPY13,
//  { BTN_TRIGGER_HAPPY14,
//  { BTN_TRIGGER_HAPPY15,
//  { BTN_TRIGGER_HAPPY16,
//  { BTN_TRIGGER_HAPPY17,
//  { BTN_TRIGGER_HAPPY18,
//  { BTN_TRIGGER_HAPPY19,
//  { BTN_TRIGGER_HAPPY20,
//  { BTN_TRIGGER_HAPPY21,
//  { BTN_TRIGGER_HAPPY22,
//  { BTN_TRIGGER_HAPPY23,
//  { BTN_TRIGGER_HAPPY24,
//  { BTN_TRIGGER_HAPPY25,
//  { BTN_TRIGGER_HAPPY26,
//  { BTN_TRIGGER_HAPPY27,
//  { BTN_TRIGGER_HAPPY28,
//  { BTN_TRIGGER_HAPPY29,
//  { BTN_TRIGGER_HAPPY30,
//  { BTN_TRIGGER_HAPPY31,
//  { BTN_TRIGGER_HAPPY32,
//  { BTN_TRIGGER_HAPPY33,
//  { BTN_TRIGGER_HAPPY34,
//  { BTN_TRIGGER_HAPPY35,
//  { BTN_TRIGGER_HAPPY36,
//  { BTN_TRIGGER_HAPPY37,
//  { BTN_TRIGGER_HAPPY38,
//  { BTN_TRIGGER_HAPPY39,
//  { BTN_TRIGGER_HAPPY40,
};
