/*
 * Copyright 2020 Toyota Connected North America
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "platform_views_handler.h"

#include <string>
#include <vector>

#include "config/common.h"  // ENABLE_PLUGINS (must precede the #if below)

#if ENABLE_PLUGINS
// Legacy compile-time platform-view dispatch (PluginsAoiPlatformViewCreate),
// generated by the external plugins framework. Only the create fallback below
// uses it; the ihs_pv/registry path needs nothing from the plugins repo.
#include <generated_plugin_registrant.h>
#endif

#include "flutter_desktop_engine_state.h"
#include "logging/logging.h"
#include "platform_view_registry.h"
#include "platform_view_touch.h"

static constexpr char kMethodCreate[] = "create";
static constexpr char kMethodDispose[] = "dispose";
static constexpr char kMethodResize[] = "resize";
static constexpr char kMethodSetDirection[] = "setDirection";
static constexpr char kMethodClearFocus[] = "clearFocus";
static constexpr char kMethodOffset[] = "offset";
static constexpr char kMethodTouch[] = "touch";
static constexpr char kMethodAcceptGesture[] = "acceptGesture";
static constexpr char kMethodRejectGesture[] = "rejectGesture";

static constexpr char kKeyId[] = "id";
static constexpr char kKeyViewType[] = "viewType";
static constexpr char kKeyDirection[] = "direction";
static constexpr char kKeyWidth[] = "width";
static constexpr char kKeyHeight[] = "height";
static constexpr char kKeyTop[] = "top";
static constexpr char kKeyLeft[] = "left";
static constexpr char kKeyParams[] = "params";
static constexpr char kKeyHybrid[] = "hybrid";

namespace {
// A platform-view method argument is either a bare integer view id (UiKitView
// sends its dispose/gesture id this way) or a map carrying an "id" key (the
// AndroidView-style create/resize messages). Resolve the id from either shape
// and from either integer width; returns false when none is present. Without
// this, a bare-int dispose fell through to id 0, so no view was unregistered
// and the surface map grew without bound.
bool ResolveViewId(const flutter::EncodableValue* arguments, int32_t& out_id) {
  if (arguments == nullptr) {
    return false;
  }
  if (const auto* v = std::get_if<int32_t>(arguments)) {
    out_id = *v;
    return true;
  }
  if (const auto* v = std::get_if<int64_t>(arguments)) {
    out_id = static_cast<int32_t>(*v);
    return true;
  }
  if (const auto* map = std::get_if<flutter::EncodableMap>(arguments)) {
    for (const auto& [key, value] : *map) {
      const auto* key_str = std::get_if<std::string>(&key);
      if (key_str == nullptr || *key_str != kKeyId) {
        continue;
      }
      if (const auto* i32 = std::get_if<int32_t>(&value)) {
        out_id = *i32;
        return true;
      }
      if (const auto* i64 = std::get_if<int64_t>(&value)) {
        out_id = static_cast<int32_t>(*i64);
        return true;
      }
    }
  }
  return false;
}

// Reads the "hybrid" flag from a map argument (absent/scalar => false).
bool ResolveHybrid(const flutter::EncodableValue* arguments) {
  if (const auto* map = std::get_if<flutter::EncodableMap>(arguments)) {
    for (const auto& [key, value] : *map) {
      const auto* key_str = std::get_if<std::string>(&key);
      if (key_str != nullptr && *key_str == kKeyHybrid) {
        if (const auto* b = std::get_if<bool>(&value)) {
          return *b;
        }
      }
    }
  }
  return false;
}

// Parses the full create request (map form) for the factory path.
PlatformViewRegistry::CreateRequest ParseCreateRequest(
    const flutter::EncodableValue* arguments,
    std::vector<uint8_t>& params_storage) {
  PlatformViewRegistry::CreateRequest req;
  const auto* map = std::get_if<flutter::EncodableMap>(arguments);
  if (map == nullptr) {
    return req;
  }
  for (const auto& [key, value] : *map) {
    const auto* key_str = std::get_if<std::string>(&key);
    if (key_str == nullptr) {
      continue;
    }
    if (*key_str == kKeyId) {
      if (const auto* v = std::get_if<int32_t>(&value)) {
        req.id = *v;
      }
    } else if (*key_str == kKeyViewType) {
      if (const auto* v = std::get_if<std::string>(&value)) {
        req.view_type = *v;
      }
    } else if (*key_str == kKeyDirection) {
      if (const auto* v = std::get_if<int32_t>(&value)) {
        req.direction = *v;
      }
    } else if (*key_str == kKeyWidth) {
      if (const auto* v = std::get_if<double>(&value)) {
        req.width = *v;
      }
    } else if (*key_str == kKeyHeight) {
      if (const auto* v = std::get_if<double>(&value)) {
        req.height = *v;
      }
    } else if (*key_str == kKeyTop) {
      if (const auto* v = std::get_if<double>(&value)) {
        req.top = *v;
      }
    } else if (*key_str == kKeyLeft) {
      if (const auto* v = std::get_if<double>(&value)) {
        req.left = *v;
      }
    } else if (*key_str == kKeyParams) {
      if (const auto* v = std::get_if<std::vector<uint8_t>>(&value)) {
        params_storage = *v;
      }
    }
  }
  req.params = &params_storage;
  return req;
}
}  // namespace

PlatformViewsHandler::PlatformViewsHandler(flutter::BinaryMessenger* messenger,
                                           FlutterDesktopEngineRef engine)
    : channel_(
          std::make_unique<flutter::MethodChannel<flutter::EncodableValue>>(
              messenger,
              "flutter/platform_views",
              &flutter::StandardMethodCodec::GetInstance())),
      engine_(engine),
      registry_(engine != nullptr ? engine->platform_view_registry.get()
                                  : nullptr) {
  channel_->SetMethodCallHandler(
      [this](const flutter::MethodCall<flutter::EncodableValue>& call,
             std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>>
                 result) { HandleMethodCall(call, std::move(result)); });
}

void PlatformViewsHandler::HandleMethodCall(
    const flutter::MethodCall<flutter::EncodableValue>& method_call,
    std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result) {
  const std::string& method_name = method_call.method_name();
  const auto arguments = method_call.arguments();

  if (arguments->IsNull()) {
    result->Error("invalid_args", "Arguments are Null");
    return;
  }
  if (registry_ == nullptr) {
    result->Error("no_registry", "Platform view registry unavailable");
    return;
  }

  if (method_name == kMethodCreate) {
    // Route to a runtime factory when one is registered for the view type;
    // otherwise fall back to the generated compile-time dispatch. With no
    // factories registered this is always the legacy path.
    std::vector<uint8_t> params_storage;
    if (const auto req = ParseCreateRequest(arguments, params_storage);
        !req.view_type.empty() && registry_->HasFactory(req.view_type)) {
      registry_->CreateViaFactory(req);
      result->Success(flutter::EncodableValue(req.id));
    } else {
#if ENABLE_PLUGINS
      PluginsAoiPlatformViewCreate(engine_, engine_->flutter_asset_directory,
                                   arguments, &PlatformViewAddListener,
                                   &PlatformViewRemoveListener, registry_,
                                   std::move(result));
#else
      // No runtime factory for this view type and no legacy plugin dispatch
      // (built without the external plugins framework).
      result->Error("no_factory",
                    "No platform-view factory registered for view type");
#endif
    }
  } else if (method_name == kMethodDispose) {
    int32_t id = 0;
    if (!ResolveViewId(arguments, id)) {
      ihs::log::warn("[PlatformViews] dispose with no resolvable id; ignoring");
      result->Success();
      return;
    }
    registry_->Dispose(id, ResolveHybrid(arguments));
    result->Success();
  } else if (method_name == kMethodResize) {
    int32_t id = 0;
    double width = 0;
    double height = 0;
    if (const auto* map = std::get_if<flutter::EncodableMap>(arguments)) {
      for (const auto& [key, value] : *map) {
        const auto* key_str = std::get_if<std::string>(&key);
        if (key_str == nullptr) {
          continue;
        }
        if (*key_str == kKeyWidth) {
          if (const auto* v = std::get_if<double>(&value)) {
            width = *v;
          }
        } else if (*key_str == kKeyHeight) {
          if (const auto* v = std::get_if<double>(&value)) {
            height = *v;
          }
        }
      }
    }
    ResolveViewId(arguments, id);
    registry_->Resize(id, width, height);
    result->Success(flutter::EncodableValue(flutter::EncodableMap{
        {flutter::EncodableValue("id"), flutter::EncodableValue(id)},
        {flutter::EncodableValue("width"), flutter::EncodableValue(width)},
        {flutter::EncodableValue("height"), flutter::EncodableValue(height)},
    }));
  } else if (method_name == kMethodSetDirection) {
    int32_t id = 0;
    int32_t direction = 0;
    if (const auto* map = std::get_if<flutter::EncodableMap>(arguments)) {
      for (const auto& [key, value] : *map) {
        const auto* key_str = std::get_if<std::string>(&key);
        if (key_str != nullptr && *key_str == kKeyDirection) {
          if (const auto* v = std::get_if<int32_t>(&value)) {
            direction = *v;
          }
        }
      }
    }
    ResolveViewId(arguments, id);
    registry_->SetDirection(id, direction);
    result->Success();
  } else if (method_name == kMethodClearFocus) {
    result->Success();
  } else if (method_name == kMethodOffset) {
    int32_t id = 0;
    double left = 0;
    double top = 0;
    if (const auto* map = std::get_if<flutter::EncodableMap>(arguments)) {
      for (const auto& [key, value] : *map) {
        const auto* key_str = std::get_if<std::string>(&key);
        if (key_str == nullptr) {
          continue;
        }
        if (*key_str == kKeyLeft) {
          if (const auto* v = std::get_if<double>(&value)) {
            left = *v;
          }
        } else if (*key_str == kKeyTop) {
          if (const auto* v = std::get_if<double>(&value)) {
            top = *v;
          }
        }
      }
    }
    ResolveViewId(arguments, id);
    registry_->SetOffset(id, left, top);
    result->Success();
  } else if (method_name == kMethodTouch && !arguments->IsNull()) {
    if (const auto* params = std::get_if<flutter::EncodableList>(arguments)) {
      const auto touch = PlatformViewTouch(*params);
      registry_->OnTouch(touch.getId(), touch.getAction(),
                         touch.getPointerCount(),
                         touch.getRawPointerCoords().size(),
                         touch.getRawPointerCoords().data());
    }
    result->Success();
  } else if (method_name == kMethodAcceptGesture && !arguments->IsNull()) {
    int32_t id = 0;
    if (ResolveViewId(arguments, id)) {
      registry_->AcceptGesture(id);
    }
    result->Success();
  } else if (method_name == kMethodRejectGesture && !arguments->IsNull()) {
    int32_t id = 0;
    if (ResolveViewId(arguments, id)) {
      registry_->RejectGesture(id);
    }
    result->Success();
  } else {
    ihs::log::error("[PlatformViews] method {} is unhandled", method_name);
    result->NotImplemented();
  }
}

void PlatformViewsHandler::PlatformViewAddListener(
    void* context,
    const int32_t id,
    const platform_view_listener* listener,
    void* listener_context) {
  static_cast<PlatformViewRegistry*>(context)->RegisterListener(
      id, listener, listener_context);
}

void PlatformViewsHandler::PlatformViewRemoveListener(void* context,
                                                      const int32_t id) {
  static_cast<PlatformViewRegistry*>(context)->UnregisterListener(id);
}
