#!/usr/bin/env python3
# Generate the config.toml reference from the parser so it cannot drift.
#
# The KEY LIST is extracted from the parser itself:
#   * shell/configuration/configuration.cc  — at_path("…").is_…()  (global + view)
#   * shell/crash_handler.cc                — ->get("…")           ([sentry])
# Human-curated metadata (default / valid values / applies-to / description)
# lives in META below. Every parsed key MUST have a META entry, or this script
# errors — so adding a key to the parser forces a doc update.
#
# Outputs:
#   docs/config-examples/reference.toml  — annotated, every key (NOT runnable)
#   README.md                            — table between the CONFIG-REFERENCE
#                                          markers (only if the markers exist)
#
# Usage:
#   scripts/gen_config_reference.py          # write the outputs
#   scripts/gen_config_reference.py --check  # exit 1 if outputs are stale (CI)

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CFG = ROOT / "shell/configuration/configuration.cc"
CRASH = ROOT / "shell/crash_handler.cc"
REFTOML = ROOT / "docs/config-examples/reference.toml"
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN CONFIG-REFERENCE (generated by scripts/gen_config_reference.py) -->"
END = "<!-- END CONFIG-REFERENCE -->"
BEGIN_CLI = "<!-- BEGIN CLI-REFERENCE (generated by scripts/gen_config_reference.py) -->"
END_CLI = "<!-- END CLI-REFERENCE -->"

TYPE = {
    "is_string": "string",
    "is_integer": "int",
    "is_boolean": "bool",
    "is_floating_point": "float",
    "is_array": "array<string>",
}

# default / values / applies / desc.  Keyed by the key as the parser spells it.
META = {
    # [global] — process-level
    "global.app_id": ("homescreen", "string", "all", "Application id (xdg app_id / agl); also argv[0] of the engine command line."),
    "global.cursor_theme": ("—", "string", "all", "XCursor theme name."),
    "global.disable_cursor": ("false", "true|false", "all", "Hide the pointer cursor."),
    "global.wayland_event_mask": ("—", "comma/space list", "wayland", "Wayland input events to mask (e.g. 'keyboard pointer')."),
    "global.debug_backend": ("false", "true|false", "all", "Enable backend debug logging."),
    # [sentry] — process-level (optional; DSN from $SENTRY_DSN)
    "sentry.release": ("—", "string", "all", "Sentry release tag."),
    "sentry.env": ("(built-in)", "string", "all", "Sentry environment."),
    "sentry.tags": ("{}", "table<string,string>", "all", "Extra Sentry tags."),
    "sentry.attachments": ("[]", "array<path>", "all", "Files attached to crash reports."),
    # [[view]] — geometry / Flutter
    "bundle": ("(from -b)", "path", "--config", "Per-view bundle directory; required in a --config master file, implicit from -b otherwise."),
    "output_index": ("0", "int", "all", "wl_output index to place the view on."),
    "width": ("1920", "int", "all", "View width in px (fallback; DRM/software adopt the panel mode)."),
    "height": ("720", "int", "all", "View height in px (fallback; DRM/software adopt the panel mode)."),
    "pixel_ratio": ("1.0", "float", "all", "Device pixel ratio override."),
    "accessibility_features": ("0", "int bitmask", "all", "FlutterAccessibilityFeature bit mask."),
    "fullscreen": ("false", "true|false", "all", "Start fullscreen."),
    # [view.args]
    "args.engine": ("[]", "array<string>", "all", "Engine / Dart VM switches -> FlutterProjectArgs.command_line_argv (app_id prepended as argv[0])."),
    "args.dart": ("[]", "array<string>", "all", "Args to the Dart entrypoint main(List<String>) -> dart_entrypoint_argv."),
    # [view.shell]
    "shell.type": ("auto", "auto|xdg|agl|ivi|simple", "all", "Wayland compositor-protocol shell."),
    "shell.surface_id": ("—", "int", "ivi", "ivi-shell numeric surface id."),
    # [view.shell.window] — AGL only
    "shell.window.type": ("NORMAL", "BG|PANEL_TOP|PANEL_BOTTOM|PANEL_LEFT|PANEL_RIGHT|NORMAL", "agl", "AGL window role."),
    # [view.shell.window.activation_area] — AGL only
    "shell.window.activation_area.x": ("0", "int", "agl", "Activation rect x (output-relative px)."),
    "shell.window.activation_area.y": ("0", "int", "agl", "Activation rect y."),
    "shell.window.activation_area.width": ("view.width", "int", "agl", "Activation rect width (omit table -> full view)."),
    "shell.window.activation_area.height": ("view.height", "int", "agl", "Activation rect height (omit table -> full view)."),
    # [view.backend]
    "backend.type": ("(env-aware)", "wayland-egl|wayland-vulkan|drm-kms-egl|drm-kms-vulkan|software", "all", "Renderer backend; unset = auto (Wayland session -> wayland-egl, else drm-kms-egl)."),
    # [view.backend.drm] — DRM/software only
    "backend.drm.device": ("(rank-pick)", "/dev/dri/cardN", "drm/sw", "DRM device node."),
    "backend.drm.connector": ("(rank-pick)", "e.g. eDP-1, HDMI-A-1", "drm/sw", "Connector to drive."),
    "backend.drm.mode": ("(preferred)", "<W>x<H>@<R>", "drm/sw", "Mode; unset = preferred from EDID."),
    "backend.drm.rotation": ("0", "0|90|180|270", "drm", "Scanout rotation in degrees."),
    "backend.drm.compositor": ("auto", "auto|planes|gl", "drm", "Compositor strategy."),
    "backend.drm.modeset": ("auto", "auto|legacy|atomic", "drm", "Modeset API."),
    "backend.drm.allow_nonblock_modeset": ("auto", "auto|yes|no", "drm", "Allow NONBLOCK|ALLOW_MODESET commits."),
    "backend.drm.primary_format": ("auto", "auto|xrgb8888|xbgr8888|argb8888|abgr8888|rgb565", "drm", "Primary plane format."),
    "backend.drm.overlay_planes": ("auto", "auto|yes|no", "drm", "Use overlay planes."),
    "backend.drm.explicit_sync": ("auto", "auto|yes|no", "drm", "Use IN_FENCE_FD / OUT_FENCE_PTR."),
    "backend.drm.async_flip": ("auto", "auto|yes|no", "drm", "Use PAGE_FLIP_ASYNC on flip-only commits."),
    "backend.drm.stage_cursor": ("auto", "auto|yes|no", "drm", "Stage HW cursor into the compositor commit (auto = nvidia-drm only)."),
    "backend.drm.no_seat": ("false", "true|false", "drm/sw", "Bypass libseat (headless/SSH/kiosk)."),
    "backend.drm.input_transforms": ("[]", "array<string>", "drm/sw", "Per-device pointer transforms '<name>=<0|90|180|270>[,flip-x][,flip-y]'."),
}

TABLE_ORDER = [
    "[global]", "[sentry]", "[[view]]", "[view.args]", "[view.shell]",
    "[view.shell.window]", "[view.shell.window.activation_area]",
    "[view.backend]", "[view.backend.drm]",
]


def classify(key):
    if key.startswith("global."):
        return "[global]", key.split(".", 1)[1]
    if key.startswith("sentry."):
        return "[sentry]", key.split(".", 1)[1]
    if key == "bundle":
        return "[[view]]", "bundle"
    if key.startswith("args."):
        return "[view.args]", key.rsplit(".", 1)[1]
    if key.startswith("shell.window.activation_area."):
        return "[view.shell.window.activation_area]", key.rsplit(".", 1)[1]
    if key.startswith("shell.window."):
        return "[view.shell.window]", key.rsplit(".", 1)[1]
    if key.startswith("shell."):
        return "[view.shell]", key.rsplit(".", 1)[1]
    if key.startswith("backend.drm."):
        return "[view.backend.drm]", key.rsplit(".", 1)[1]
    if key.startswith("backend."):
        return "[view.backend]", key.rsplit(".", 1)[1]
    return "[[view]]", key


def extract():
    keys = {}
    text = CFG.read_text()
    for m in re.finditer(r'at_path\("([^"]+)"\)\s*\.\s*(is_\w+)\(\)', text):
        key, t = m.group(1), m.group(2)
        if key == "view":
            continue
        keys.setdefault(key, TYPE.get(t, t))
    # [sentry] keys (different parse style in crash_handler.cc)
    crash = CRASH.read_text()
    sentry_section = crash[crash.find('get("sentry")'):]
    for m in re.finditer(r'get\("([^"]+)"\)', sentry_section):
        k = m.group(1)
        if k == "sentry":
            continue
        keys.setdefault("sentry." + k, "string")
    return keys


def build():
    keys = extract()
    missing = sorted(k for k in keys if k not in META)
    if missing:
        sys.stderr.write(
            "error: parser keys with no META entry (update scripts/"
            "gen_config_reference.py):\n  " + "\n  ".join(missing) + "\n")
        sys.exit(2)
    stale = sorted(k for k in META if k not in keys)
    if stale:
        sys.stderr.write(
            "warning: META entries no longer parsed (remove them):\n  "
            + "\n  ".join(stale) + "\n")

    rows = {t: [] for t in TABLE_ORDER}
    for key in keys:
        table, name = classify(key)
        default, values, applies, desc = META[key]
        rows[table].append((name, keys[key], default, values, applies, desc, key))
    for t in rows:
        rows[t].sort(key=lambda r: r[6])
    return rows


def render_table(rows):
    # Escape '|' so it doesn't split the markdown table cell, and wrap the
    # type/values cells in backticks so '<...>' isn't read as HTML.
    def cell(s):
        return "`" + s.replace("|", "\\|") + "`"

    out = [
        "| table | key | type | default | values | applies to |",
        "|---|---|---|---|---|---|",
    ]
    for table in TABLE_ORDER:
        for name, typ, default, values, applies, desc, _ in rows[table]:
            out.append(f"| `{table}` | `{name}` | {cell(typ)} | {cell(default)} "
                       f"| {cell(values)} | {applies} |")
    return "\n".join(out)


def render_reftoml(rows):
    out = [
        "# config.toml — REFERENCE. Lists every key the parser reads, grouped by",
        "# table, with type / default / valid values / applies-to. This file is a",
        "# reference, NOT runnable as-is: AGL window/activation keys, ivi surface_id",
        "# and the DRM knobs are mutually exclusive by shell/backend. For runnable",
        "# configs see the other files in this directory. Generated by",
        "# scripts/gen_config_reference.py — do not edit by hand.",
        "",
    ]
    for table in TABLE_ORDER:
        if not rows[table]:
            continue
        out.append(table)
        for name, typ, default, values, applies, desc, _ in rows[table]:
            out.append(f"  # {desc}")
            out.append(f"  # type={typ} default={default} values={values} applies={applies}")
            out.append(f"  {name} =")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def capture_help():
    # The binary's --help is the source of truth for the CLI. Returns a fenced
    # code block, or None if no binary is available (skip, don't fail).
    for b in (ROOT / "cmake-build-debug/shell/homescreen",
              ROOT / "build/shell/homescreen"):
        if not b.exists():
            continue
        try:
            r = subprocess.run([str(b), "--help"], capture_output=True,
                               text=True, timeout=15)
        except Exception:
            return None
        out = (r.stdout or "") + (r.stderr or "")
        lines = [re.sub(r"^\[[0-9:.]+\] \[\w\] ", "", ln)
                 for ln in out.splitlines()]
        text = "\n".join(lines)
        i = text.find("Usage:")
        if i >= 0:
            text = text[i:]
        return "```text\n" + text.strip() + "\n```"
    return None


def replace_block(text, begin, end, body):
    if begin in text and end in text:
        pre = text[: text.index(begin) + len(begin)]
        post = text[text.index(end):]
        return pre + "\n\n" + body + "\n\n" + post
    return None


def main():
    check = "--check" in sys.argv[1:]
    rows = build()
    reftoml = render_reftoml(rows)
    table = render_table(rows)

    changed = []
    if (not REFTOML.exists()) or REFTOML.read_text() != reftoml:
        changed.append(str(REFTOML.relative_to(ROOT)))

    readme = README.read_text() if README.exists() else ""
    new_readme = readme
    r = replace_block(new_readme, BEGIN, END, table)
    if r is not None:
        new_readme = r
    else:
        sys.stderr.write("note: README.md has no CONFIG-REFERENCE markers; "
                         "skipping config table.\n")
    cli = capture_help()
    if cli is None:
        sys.stderr.write("note: no homescreen binary found "
                         "(cmake-build-debug/ or build/); skipping CLI block.\n")
    else:
        r = replace_block(new_readme, BEGIN_CLI, END_CLI, cli)
        if r is not None:
            new_readme = r
        else:
            sys.stderr.write("note: README.md has no CLI-REFERENCE markers; "
                             "skipping CLI block.\n")
    if new_readme != readme:
        changed.append("README.md")

    if check:
        if changed:
            sys.stderr.write("config reference is STALE; run "
                             "scripts/gen_config_reference.py:\n  "
                             + "\n  ".join(changed) + "\n")
            sys.exit(1)
        print("config reference up to date")
        return

    REFTOML.parent.mkdir(parents=True, exist_ok=True)
    REFTOML.write_text(reftoml)
    if new_readme != readme:
        README.write_text(new_readme)
    print("wrote " + ", ".join(changed) if changed else "nothing to update")


if __name__ == "__main__":
    main()
