name: flutter-auto-linux

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

env:
  COMPONENT: flutter-auto

jobs:
  build:
    if: ${{ github.server_url == 'https://github.com' &&  always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          echo ${{ github.server_url }}
          sudo add-apt-repository -y ppa:kisak/kisak-mesa
          sudo apt update -y
          sudo apt-get -y install libwayland-dev wayland-protocols \
          mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev mesa-utils \
          libc++-11-dev libc++abi-11-dev libunwind-dev libxkbcommon-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          gstreamer1.0-plugins-base gstreamer1.0-gl libavformat-dev
          clang++ --version
          cmake --version

      - name: Configure
        run: |
          mkdir -p ${{github.workspace}}/build/release
          CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake \
            -B ${{github.workspace}}/build/release \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_STAGING_PREFIX=${{github.workspace}}/build/staging/usr/local \
            -D BUILD_NUMBER=${GITHUB_RUN_ID}
          mkdir -p ${{github.workspace}}/build/debug
          CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake \
            -B ${{github.workspace}}/build/debug \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_STAGING_PREFIX=${{github.workspace}}/build/staging/usr/local \
            -D BUILD_NUMBER=${GITHUB_RUN_ID}

      - name: Build Debug Packages
        working-directory: ${{github.workspace}}/build/debug
        run: |
          rm -rf _packages || true
          make package -j
          ls -la _packages

      - name: Publish Debug Artifact TGZ
        uses: actions/upload-artifact@v2
        with:
          name: flutter-auto-dbg.Linux.tar.gz.zip
          path: |
            build/debug/_packages/flutter-auto-dbg-*-Linux.tar.gz

      - name: Publish Debug Artifact Debian
        uses: actions/upload-artifact@v2
        with:
          name: flutter-auto-dbg.amd64.deb.zip
          path: |
            build/debug/_packages/flutter-auto-dbg*_amd64.*deb

      - name: Publish Debug Artifact RPM
        uses: actions/upload-artifact@v2
        with:
          name: flutter-auto-dbg.x86_64.rpm.zip
          path: |
            build/debug/_packages/flutter-auto-dbg-*.x86_64.rpm

      - name: Build Release Packages
        working-directory: ${{github.workspace}}/build/release       
        run: |
          rm -rf _packages || true
          make package -j
          ls -la _packages
          echo "Release Info"
          ls -la shell/flutter-auto
          echo "Strip executable"
          strip shell/flutter-auto
          ls -la shell/flutter-auto
          echo "List Dependencies"
          ldd shell/flutter-auto

      - name: Publish Release Artifact TGZ
        uses: actions/upload-artifact@v2
        with:
          name: flutter-auto.Linux.tar.gz.zip
          path: |
            build/release/_packages/flutter-auto-*-Linux.tar.gz

      - name: Publish Release Artifact Debian
        uses: actions/upload-artifact@v2
        with:
          name: flutter-auto.amd64.deb.zip
          path: |
            build/release/_packages/flutter-auto_*_amd64.deb

      - name: Publish Release Artifact RPM
        uses: actions/upload-artifact@v2
        with:
          name: flutter-auto.x86_64.rpm.zip
          path: |
            build/release/_packages/flutter-auto-*.x86_64.rpm
