name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [v2.0]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.server_url == 'https://github.com' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
            version: '12'
            cc: gcc-12
            cxx: g++-12
            extra_pkgs: g++-12
          - compiler: gcc
            version: '13'
            cc: gcc-13
            cxx: g++-13
            extra_pkgs: g++-13
          - compiler: gcc
            version: '14'
            cc: gcc-14
            cxx: g++-14
            extra_pkgs: g++-14
          - compiler: clang
            version: '19'
            cc: clang-19
            cxx: clang++-19
            extra_pkgs: clang-19 llvm-19 lld-19 libc++-19-dev libc++abi-19-dev
          - compiler: clang
            version: '20'
            cc: clang-20
            cxx: clang++-20
            extra_pkgs: clang-20 llvm-20 lld-20 libc++-20-dev libc++abi-20-dev

    name: ${{ matrix.compiler }}-${{ matrix.version }}
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ninja-build libwayland-dev wayland-protocols libxkbcommon-dev mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev mesa-utils libglib2.0-dev libpugixml-dev ${{ matrix.extra_pkgs }}
          version: 1.0

      - name: Configure
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          cmake -GNinja \
            -B ${{github.workspace}}/build \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -D BUILD_NUMBER=${GITHUB_RUN_ID}

      - name: Build
        run: ninja -C ${{github.workspace}}/build

  lint:
    if: ${{ github.server_url == 'https://github.com' }}
    runs-on: ubuntu-24.04
    name: lint
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ninja-build libwayland-dev wayland-protocols libxkbcommon-dev mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev mesa-utils libglib2.0-dev libpugixml-dev clang-19 clang-tidy-19 clang-format-19 llvm-19 lld-19 libc++-19-dev libc++abi-19-dev
          version: 1.0

      - name: Configure
        env:
          CC: clang-19
          CXX: clang++-19
        run: |
          cmake -GNinja \
            -B ${{github.workspace}}/build \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -D BUILD_NUMBER=${GITHUB_RUN_ID}

      - name: Build (generate compile_commands.json)
        run: ninja -C ${{github.workspace}}/build

      - name: clang-tidy
        run: scripts/clang_tidy.sh ${{github.workspace}}/build

      - name: clang-format
        run: scripts/format.sh --check